version: '3'
services:
  app:
    build: docker/node
    expose:
      - 80
      - 443
    volumes:
      - ./src/:/app/
    working_dir: /app/
    entrypoint: npm run start
    environment:
      VIRTUAL_HOST: hnkr.ghostserver.jp
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true